# Generated by Django 3.2.18 on 2023-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaging',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
