# Generated by Django 5.0 on 2023-12-12 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_messaging_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
