# Generated by Django 5.0 on 2023-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_pfp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pfp',
        ),
    ]
