# Generated by Django 5.0 on 2023-12-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pim',
            name='bio',
            field=models.CharField(default='', max_length=150),
        ),
    ]
