# Generated by Django 5.0 on 2024-03-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsystem', '0003_alter_pim_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pim',
            name='profilepic',
        ),
    ]
