# Generated by Django 5.0 on 2024-03-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsystem', '0004_remove_pim_profilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pim',
        ),
    ]
