# Generated by Django 5.0 on 2024-03-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsystem', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
