# Generated by Django 5.0 on 2024-03-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsystem', '0009_cred_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cred',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
