# Generated by Django 5.0 on 2024-03-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsystem', '0010_cred_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cred',
            name='otp_ver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
